CREATE TABLE tb_mhsw (
	mhsw_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	mhsw_nim VARCHAR(20) NOT NULL,
	mhsw_nama VARCHAR(100) NOT NULL,
	mhsw_alamat TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT NULL, 
	PRIMARY KEY(mhsw_id),
	UNIQUE KEY(mhsw_nim)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;